// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3KHDEmQkuLtU4Bm6YSEeuNCBKMWZD6mg',
    appId: '1:34564683848:web:797bd28d8cdf6ad80d407d',
    messagingSenderId: '34564683848',
    projectId: 'flutter-sample-roggle',
    authDomain: 'flutter-sample-roggle.firebaseapp.com',
    storageBucket: 'flutter-sample-roggle.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGMu4vbbXuW8S8z0fg9tMKSm6-kGGsYAc',
    appId: '1:34564683848:android:0e8d3d8055f839850d407d',
    messagingSenderId: '34564683848',
    projectId: 'flutter-sample-roggle',
    storageBucket: 'flutter-sample-roggle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR2iJBgj1JEKwNwTGNRMUPnsoKQ2l8XRs',
    appId: '1:34564683848:ios:ff2ba15c5951d7a10d407d',
    messagingSenderId: '34564683848',
    projectId: 'flutter-sample-roggle',
    storageBucket: 'flutter-sample-roggle.appspot.com',
    iosClientId: '34564683848-hctbjfimpjf3b762b12ft90mmmp6gpll.apps.googleusercontent.com',
    iosBundleId: 'jp.susatthi.flutterSampleRoggle',
  );
}
